spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/example?serverTimezone=Asia/Seoul"
    username: root #ssoadmin
    password: 1234 #dlswmdtjqj
#    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        show-sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        use_sql_comments: true
      connection:
        characterEncoding: utf-8
        CharSet: utf-8
        useUnicode: true
logging:
  level:
    org.springframework: INFO
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
server:
  port: 9090